import type { ComposerId } from "@/types/music";

export type ComposerProfile = {
  id: ComposerId;
  title: string;
  dna: string[];
  skeleton: string[];
  bassSchemata: string[];
  cadencePool: Array<{ name: string; weight: number }>;
  modulationPool: Array<{ name: string; weight: number }>;
  sonorityPool: Array<{ name: string; weight: number }>;
  avoid: string[];
};

const p = (name: string, weight: number) => ({ name, weight });

export const profiles: Record<ComposerId, ComposerProfile> = {
  beethoven: { id: "beethoven", title: "Beethoven", dna: ["structural conflict", "dominant pressure", "cadential force"], skeleton: ["I", "V/V→V", "vi", "HC", "circle", "Ger+6", "cad64→V7", "I"], bassSchemata: ["rule-of-octave variant", "1-7-6-5", "circle of fifths", "dominant pedal"], cadencePool: [p("PAC", 3), p("HC", 3), p("deceptive", 2)], modulationPool: [p("dominant", 3), p("relative", 2), p("diminishedPivot", 2)], sonorityPool: [p("triad", 3), p("V7", 3), p("Ger+6", 2), p("N6", 1)], avoid: ["floating anti-cadence"] },
  schubert: { id: "schubert", title: "Schubert", dna: ["third-relations", "mixture", "lyrical distance"], skeleton: ["I", "♭VI/♭III", "common-tone", "soft HC", "descending thirds", "mixture", "plagal prep", "soft I"], bassSchemata: ["1-♭6", "descending thirds", "lyric stepwise descent"], cadencePool: [p("softPAC", 2), p("deceptive", 3), p("plagal", 2)], modulationPool: [p("chromaticMediant", 3), p("commonTone", 3), p("flatSide", 2)], sonorityPool: [p("mixture", 3), p("flatVI", 3), p("commonToneDim", 2)], avoid: ["hard mechanical closure"] },
  hummel: { id: "hummel", title: "Hummel", dna: ["classical clarity", "clean syntax", "elegance"], skeleton: ["I→V6", "ii6→V", "I6→IV", "cad64→V", "circle", "applied V", "cad64→V7", "I"], bassSchemata: ["rule-of-octave variant", "1-2-3-4-5", "1-7-6-5"], cadencePool: [p("PAC", 3), p("HC", 2), p("lightDeceptive", 1)], modulationPool: [p("dominant", 3), p("relative", 3), p("cleanPivot", 3)], sonorityPool: [p("triad", 3), p("V7", 3), p("appliedDominant", 2)], avoid: ["wagnerian ambiguity"] },
  chopin: { id: "chopin", title: "Chopin", dna: ["bel canto", "chromatic bass", "ornamental cadence"], skeleton: ["I(add color)", "vi/IV appogg", "N6/Ger+6", "V9 HC", "dim sequence", "minor iv", "V13 suspension", "I delayed"], bassSchemata: ["chromatic descent", "lament", "pedal with chromatic upper"], cadencePool: [p("ornamentalPAC", 3), p("delayedMelodic", 3), p("deceptive", 2)], modulationPool: [p("enharmonicDim", 3), p("chromaticBass", 3), p("commonTone", 2)], sonorityPool: [p("V9", 3), p("V13", 2), p("N6", 2), p("appoggiaturaChord", 3)], avoid: ["square classical syntax"] },
  mendelssohn: { id: "mendelssohn", title: "Mendelssohn", dna: ["counterpoint", "clarity", "chorale discipline"], skeleton: ["I→IV6", "ii6→V", "relative pivot", "HC", "sequence", "suspensions", "cad64→V", "I/plagal"], bassSchemata: ["diatonic rule-of-octave", "walking bass", "pedal"], cadencePool: [p("PAC", 3), p("plagal", 2), p("choraleCadence", 3)], modulationPool: [p("diatonicPivot", 3), p("relative", 3), p("sequence", 2)], sonorityPool: [p("triad", 3), p("suspension", 3), p("pedal64", 2)], avoid: ["uncontrolled chromaticism"] },
  schumann: { id: "schumann", title: "Schumann", dna: ["psychological blur", "fragment", "displaced cadence"], skeleton: ["I→V6", "vi/♭VI", "common-tone mediant", "HC/deceptive", "fragment sequence", "minor iv", "displaced cadence", "blurred I"], bassSchemata: ["relative turn", "chromatic descent", "pedal blur"], cadencePool: [p("blurredPAC", 3), p("deceptive", 3), p("displacedCadence", 3)], modulationPool: [p("characterKey", 3), p("commonTone", 3), p("chromaticMediant", 2)], sonorityPool: [p("minorIv", 3), p("flatVI", 3), p("suspensionBlur", 3)], avoid: ["clean Hummel closure"] },
  brahms: { id: "brahms", title: "Brahms", dna: ["compressed counterpoint", "suspensions", "weighted cadence"], skeleton: ["I 6/3", "5-6 sequence", "modal color", "suspension HC", "descending thirds", "Ger+6/♭VI", "hemiola cad64→V", "weighted I"], bassSchemata: ["5-6 sequence", "descending thirds", "1-♭7-♭6-5"], cadencePool: [p("weightedPAC", 3), p("suspensionCadence", 3), p("hemiola", 2)], modulationPool: [p("thirdChain", 3), p("modalShift", 3), p("bassSequence", 2)], sonorityPool: [p("suspension76", 3), p("motion56", 3), p("Ger+6", 2), p("flatVI", 3)], avoid: ["empty virtuosity"] },
  wagner: { id: "wagner", title: "Wagner", dna: ["deferral", "dominant field", "enharmonic transformation"], skeleton: ["ambiguous appoggiatura", "altered dominant", "chromatic mediant", "avoided HC", "dominant field", "augmented-sixth portal", "V9/♭9 delay", "deceptive/redemption"], bassSchemata: ["chromatic ascent", "tritone bass", "dominant pedal"], cadencePool: [p("avoided", 3), p("dominantField", 3), p("redemptionPlagal", 2)], modulationPool: [p("enharmonic", 3), p("tritone", 3), p("aug6Portal", 2)], sonorityPool: [p("tristanType", 3), p("Vb9", 3), p("V13", 2), p("halfDiminished", 3)], avoid: ["early V-I closure"] },
  rachmaninoff: { id: "rachmaninoff", title: "Rachmaninoff", dna: ["bell resonance", "dark bass", "dominant wave"], skeleton: ["i(add6)", "VI/iv bell", "♭VII/mediant", "V9 HC", "diminished sequence", "N6/Ger+6", "cad64→V♭9", "i(add6)"], bassSchemata: ["1-♭7-♭6-5", "dominant pedal wave", "descending thirds"], cadencePool: [p("hugeV9", 3), p("tragicMinor", 3), p("bellPlagal", 2)], modulationPool: [p("flatVI", 3), p("diminishedSequence", 3), p("dominantWave", 3)], sonorityPool: [p("add6", 3), p("add9", 2), p("Vb9", 3), p("bellChord", 3)], avoid: ["thin texture"] },
  scriabin: { id: "scriabin", title: "Scriabin", dna: ["synthetic field", "tritone axis", "anti-cadence"], skeleton: ["Mystic field", "field transposition", "third-axis field", "suspended field", "minor-third cycle", "acoustic→octatonic", "ecstatic dominant", "dissolution"], bassSchemata: ["C→F# field", "minor-third cycle", "whole-tone field"], cadencePool: [p("antiCadence", 3), p("fieldDissolution", 3), p("weakenedCadence", 2)], modulationPool: [p("tritoneAxis", 3), p("minorThirdCycle", 3), p("mysticTransposition", 3)], sonorityPool: [p("mystic", 3), p("V13sharp11", 3), p("octatonicField", 3), p("quartalDominant", 3)], avoid: ["ordinary cad64"] }
};
