import type { HarmonyPlan, NoteEvent, Pitch, VoiceLine } from "@/types/music";

function pitchXml(p: Pitch) {
  return `<pitch><step>${p.step}</step>${p.alter !== 0 ? `<alter>${p.alter}</alter>` : ""}<octave>${p.octave}</octave></pitch>`;
}

function durationType(divisions: number, value: string) {
  const mapping: Record<string, { duration: number; type: string; dot?: boolean }> = {
    whole: { duration: divisions * 4, type: "whole" },
    "dotted-half": { duration: divisions * 3, type: "half", dot: true },
    half: { duration: divisions * 2, type: "half" },
    "dotted-quarter": { duration: Math.round(divisions * 1.5), type: "quarter", dot: true },
    quarter: { duration: divisions, type: "quarter" },
    eighth: { duration: Math.round(divisions / 2), type: "eighth" }
  };
  return mapping[value] ?? mapping.quarter;
}

function notesByBar(notes: NoteEvent[]) {
  const map = new Map<number, NoteEvent[]>();
  for (const n of notes) {
    const list = map.get(n.bar) ?? [];
    list.push(n);
    map.set(n.bar, list);
  }
  for (const list of map.values()) {
    list.sort((a, b) => a.beat - b.beat);
  }
  return map;
}

function voiceMeasureXml(notes: NoteEvent[], voiceNo: number) {
  return notes
    .map((n) => {
      const d = durationType(n.duration.divisions, n.duration.value);
      return `<note>${pitchXml(n.pitch)}<duration>${d.duration}</duration><voice>${voiceNo}</voice><type>${d.type}</type>${d.dot ? "<dot/>" : ""}<staff>${voiceNo <= 2 ? 1 : 2}</staff></note>`;
    })
    .join("");
}

export function serializeMusicXML(plan: Omit<HarmonyPlan, "musicXml">): string {
  const divisions = 4;
  const allNotes = plan.voices.flatMap((v) => v.notes);
  const bars = notesByBar(allNotes);
  const voices: VoiceLine[] = plan.voices;

  const measures = Array.from({ length: 8 }, (_, idx) => {
    const bar = idx + 1;
    const attrs =
      bar === 1
        ? `<attributes><divisions>${divisions}</divisions><key><fifths>0</fifths></key><time><beats>4</beats><beat-type>4</beat-type></time><staves>2</staves><clef number="1"><sign>G</sign><line>2</line></clef><clef number="2"><sign>F</sign><line>4</line></clef></attributes><direction placement="above"><direction-type><words>2+2+4 phrase</words></direction-type></direction>`
        : "";

    const voiceChunks = voices
      .map((voice, i) => ({ i, notes: voice.notes.filter((n) => n.bar === bar) }))
      .filter((v) => v.notes.length > 0)
      .map((v) => voiceMeasureXml(v.notes, v.i + 1));

    const joined = voiceChunks.join(`<backup><duration>${divisions * 4}</duration></backup>`);
    const finalBarline = bar === 8 ? `<barline location="right"><bar-style>light-heavy</bar-style></barline>` : "";

    return `<measure number="${bar}">${attrs}${joined || `<note><rest/><duration>${divisions * 4}</duration><voice>1</voice><type>whole</type></note>`}${finalBarline}</measure>`;
  }).join("");

  return `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 4.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="4.0">
  <work><work-title>8-bar study after ${plan.composer}</work-title></work>
  <identification><encoding><software>Generated by Romantic Harmony Generator</software></encoding></identification>
  <part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list>
  <part id="P1">${measures}</part>
</score-partwise>`;
}
